<?php

$labels = array(
  'name' => _x('New', 'General name', 'bluetide'),
  'singular_name' => _x('New', 'Singular name', 'bluetide'),
  'menu_name' => __('News', 'bluetide'),
  'name_admin_bar' => __('New', 'bluetide'),
  'archives' => __('Item Archives', 'bluetide'),
  'attributes' => __('Item Attributes', 'bluetide'),
  'parent_item_colon' => __('Parent Item:', 'bluetide'),
  'all_items' => __('All news', 'bluetide'),
  'add_new_item' => __('Add new new', 'bluetide'),
  'add_new' => __('Add new', 'bluetide'),
  'new_item' => __('new new', 'bluetide'),
  'edit_item' => __('Edit new', 'bluetide'),
  'update_item' => __('Update new', 'bluetide'),
  'view_item' => __('View new', 'bluetide'),
  'view_items' => __('View news', 'bluetide'),
  'search_items' => __('Search news', 'bluetide'),
  'not_found' => __('No news found', 'bluetide'),
  'not_found_in_trash' => __('No news found in the trash', 'bluetide'),
  'featured_image' => __('Featured image', 'bluetide'),
  'set_featured_image' => __('Add featured image', 'bluetide'),
  'remove_featured_image' => __('Remove featured image', 'bluetide'),
  'use_featured_image' => __('Use as featured image', 'bluetide'),
  'insert_into_item' => __('Insert to news', 'bluetide'),
  'uploaded_to_this_item' => __('Upload to new', 'bluetide'),
  'items_list' => __('List of news', 'bluetide'),
  'items_list_navigation' => __('Navigate to list of news', 'bluetide'),
  'filter_items_list' => __('Filter list of news', 'bluetide'),
);
$args = array(
  'label' => __('New', 'bluetide'),
  'description' => __('new description', 'bluetide'),
  'labels' => $labels,
  'supports' => array('title', 'editor', 'thumbnail'),
  'hierarchical' => false,
  'public' => false,
  'show_ui' => true,
  'show_in_menu' => true,
  'menu_position' => 5,
  'can_export' => true,
  'has_archive' => true,
  'exclude_from_search' => false,
  'publicly_queryable' => true,
  'map_meta_cap' => true,
  'query_var' => true,
  'rewrite' => array('slug' => 'news'),
  'menu_icon' => 'dashicons-text-page',
  'show_in_rest' => false,
  'rest_base' => 'news',
  'capability_type' => 'post',
  'taxonomies' => array('category'),
);
register_post_type('new', $args);
